### ISSUE TITLE
Roadmap for new version 

### ISSUE THREAD

**Issue by mabasic** [laravelista/picasso#5]
- [ ] Better package name.
- [ ] Package should log missing optimized images not throw an exception.
- [ ] The package should try to get the optimized image, but it should fallback to the original image.
- [ ] The package should be able to integrate with models, so that the developer can query if the optimized image is available and get all optimized images etc.
- [ ] The package should be able to handle optimizing "static" images
- [ ] The original images should be kept private by default, but should also be able to be kept public.
- [ ] Maybe implement spatie package for image optimization?
